-- Table: sba_loans

DROP TABLE IF EXISTS sba_loans;

CREATE TABLE IF NOT EXISTS sba_loans
(
    "as_of_date" date,
    "program" character varying(3),
    "borr_name" text,
    "borr_street" text,
    "borr_city" text,
    "borr_state" character varying(2),
    "borr_zip" character(5),
    "location_id" character(7),
    "bank_name" text,
    "bank_fdic_number" character varying(10),
    "bank_ncua_number" character varying(10),
    "bank_street" text,
    "bank_city" text,
    "bank_state" character varying(2),
    "bank_zip" character(5),
    "gross_approval" numeric(10,2),
    "sba_guaranteed_Approval" numeric(10,2),
    "approval_date" date,
    "approval_fy" smallint,
    "first_disbursement_date" text,
    "processing_method" text,
    "subprogram" text,
    "initial_interest_rate" numeric(8,5),
    "fixed_or_variable_interest_rate" character varying(1),
    "term_in_months" smallint,
    "naics_code" character varying(6),
    "naics_description" text,
    "franchise_code" character varying(10),
    "franchise_name" text,
    "project_county" text,
    "project_state" character varying(2),
    "sba_district_office" text,
    "congressional_district" smallint,
    "business_type" character varying(20),
    "business_age" text,
    "loan_status" character varying(20),
    "paid_in_full_date" text,
    "charge_off_date" date,
    "gross_charge_off_amount" numeric(10,2),
    "revolver_status" character(1),
    "jobs_supported" float,
    "collateral_ind" character(1),
    "sold_second_market_ind" character(1) 
);